export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const LOAD_BOOKS_FAIL = 'LOAD_BOOKS_FAIL';
export const SET_QUERY = 'SET_QUERY';
export const SET_QUERYTYPE = 'SET_QUERYTYPE';
export const CLEAR_BOOKS = 'CLEAR_BOOKS';
export const IS_MOREBOOKS_AVAILABLE = 'IS_MOREBOOKS_AVAILABLE';
